**Introduction to NumPy**

**Problem 1:**

In [8]:
import numpy as np 

#Write a function that defines the following matrices as NumPy arrays
def problem_1(x, y):
    return x @ y

A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
problem_1(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

**Problem 2:**

In [15]:
# Write a function that defines the following matrix as a NumPy array.
def problem_2(x):
    answer = -x @ -x @ -x + 9 * x @ x - 15 * x
    return answer

A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
problem_2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Problem 3:**

In [27]:
# Write a function that defines the following matrices as NumPy arrays using the functions presented in this section.  
def problem_3(A, B):
    One = np.ones(7)
    A = np.triu(One)
    Five = np.full_like(A, 6)
    B = np.triu(Five) - 1
    answer = A @ B @ A
    answer = answer.astype(np.int64)
    return answer
problem_3(A, B)

array([[ -1,   4,  15,  32,  55,  84, 119],
       [ -6,  -6,   0,  12,  30,  54,  84],
       [ -5, -10,  -9,  -2,  11,  30,  55],
       [ -4,  -8, -12, -10,  -2,  12,  32],
       [ -3,  -6,  -9, -12,  -9,   0,  15],
       [ -2,  -4,  -6,  -8, -10,  -6,   4],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -1]])

**Problem 4:**

In [34]:
#Write a function that accepts a single array as input.
def problem_4(X):
    copy = np.copy(X)
    mask = copy < 0 
    copy[mask] = 0 
    return copy
problem_4(problem_3(A, B))

array([[  0,   4,  15,  32,  55,  84, 119],
       [  0,   0,   0,  12,  30,  54,  84],
       [  0,   0,   0,   0,  11,  30,  55],
       [  0,   0,   0,   0,   0,  12,  32],
       [  0,   0,   0,   0,   0,   0,  15],
       [  0,   0,   0,   0,   0,   0,   4],
       [  0,   0,   0,   0,   0,   0,   0]])

**Problem 5:**

In [56]:
#Write a function that
def problem_5():
    A = np.arange(6).reshape((3,2)).T
    I = np.eye(3)
    B = np.tril(np.full_like(I,3))
    C = np.diag([-2, -2, -2])
    x1 = np.vstack((np.zeros((3,3)), A, B))
    x2 = np.vstack((A.T, np.zeros((2,2)), np.zeros((3,2))))
    x3 = np.vstack((I, np.zeros((2,3)), C))
    answer = np.hstack((x1,x2,x3))
    answer = answer.astype(np.int64)
    return answer
problem_5()

array([[ 0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  2,  3,  0,  1,  0],
       [ 0,  0,  0,  4,  5,  0,  0,  1],
       [ 0,  2,  4,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]])

**Problem 6:**

In [86]:
def problem_6(X):
    summed = X.sum(axis=1)
    colsum = summed.reshape(-1,1)
    answer = X / colsum
    return answer
mat = np.arange(6).reshape((2,3))
problem_6(mat)


array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667]])

**Problem 7:**

In [1]:
import numpy as np
def max_numbers():
    grid = np.load("grid.npy")
    maxright = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    maxup = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    maxrightdiag = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    maxleftdiag = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    maxes = [maxright, maxup, maxrightdiag, maxleftdiag]
    
    return maxes
max_numbers()

[48477312, 51267216, 40304286, 70600674]