# Problem Set #3: Decomposition

## QR Decomposition:

### Problem 1[Fix]]

In [25]:
from scipy import linalg as la
import numpy as np

def QRdecom(A):
    m, n = A.shape
    Q = np.copy(A)
    R = np.zeros((n,n))
    for i in range(n):
        R[i,i] = la.norm(A[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        for j in range(n):
            R[i,j] = Q[:, j].T @ Q[:, i]
            Q[:,j] = Q[:,j] - (R[i, j] * Q[:, i])
    return Q, R
m, n = 6, 4
A = np.random.random((m,n))
Q, R = QRdecom(A)
Q2, R2 = la.qr(A, mode='economic')
print(Q2, "\n\n", R2, "\n")

print(Q, "\n\n", R, "\n")
print(np.allclose(np.triu(R), R))
print(np.allclose(Q.T @ Q, np.identity(n)))
print(np.allclose(Q @ R, A))


[[-0.28895041  0.15805993  0.55828374  0.74900783]
 [-0.5665607  -0.27245354 -0.23527846 -0.07940025]
 [-0.65849091 -0.36836893  0.06263079 -0.14180955]
 [-0.20984914  0.43861448  0.33275132 -0.33396764]
 [-0.2503625   0.51534823 -0.70266167  0.35815143]
 [-0.23492191  0.55418769  0.15679236 -0.41565142]] 

 [[-1.47387337 -1.63092263 -1.31058918 -1.70982885]
 [ 0.          0.67174618  0.58839524  0.67931909]
 [ 0.          0.          0.8770218  -0.15153499]
 [ 0.          0.          0.         -0.52563108]] 

[[-4.24183357e-18  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.25150143e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.37243828e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.16097472e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.44521956e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.43468944e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 

 [[ 1.00000000e+00  3.25252268e-16  2.62399622e-16  3.42934006e-16]
 [ 1.84399

### Problem 2[[Fix]]

In [32]:
def detQR(A):
    Q, R = la.qr(A, mode='economic')
    return abs(np.prod(np.diag(R)))
determinant = lambda A: abs(np.prod(np.diag(R)))  
m, n = 4, 4
A = np.random.random((m,n))
detQR(A)
la.det(A)
print(determinant,  detQR(A) )

<function <lambda> at 0x10f840a60> 0.03347519845202254


### Problem 3

In [ ]:
def NLS(A, b):
    Q, R = la.qr(A, mode='economic')
    y = Q.T @ b
    return la.inv(R) @ y
m, n = 4, 4
A = np.random.random((m,n))

### Problem 4

### Problem 5