## Problem 9.6

In [99]:
import numpy as np
import random as rand
from scipy import linalg as la

In [100]:
def steepest_descent(Q, b, c, x_0, eps=1e-6, maxiter=10):
    f = lambda x: x.T @ Q @ x - b.T @ x + c
    fprime = lambda x:  (Q + Q.T) @ x.T  - b
    # I'm confused with what the actual function is.  The function given doesn't converge.
    # whereas the general function does.  
    fprime = lambda x: .5 *  x.T @ (Q.T + Q)  + b.T
    x_k = x_0
    i = 0
    dist = 1
    while dist > epsilon and i < maxiter:
        alpha_k = (fprime(x_k) @ fprime(x_k).T) / (fprime(x_k) @ Q @ fprime(x_k).T)
        x_kp1 = x_k - alpha_k * fprime(x_k).T
        dist = np.linalg.norm(fprime(x_kp1))
        x_k = np.copy(x_kp1)
        i += 1
    return x_k, i

In [101]:
Q = np.array([[2, 1], [1, 2]])
b = np.array([-2, 1])
c = 0
x_0 = np.array([23, 7])
steepest_descent(Q, b, c, x_0)

(array([ 1.66666695, -1.33333322]), 10)

## Problem 9.7

In [102]:
def DF_forward_diff(f, x, err):
    if np.isscalar(f(x)):
        m = 1
    else:
        m = len(f(x))
    if np.isscalar(x):
        n = 1
    else:
        n = len(x)
    df = np.empty((m, n))
    e = np.eye(n)
    h = np.sqrt(err)
    for i in range(n):
        df[:, i] = (f(x + h*e[i]) - f(x - h*e[i])) / (2*h)
    return df
f = lambda x: np.array([x[0] ** 2 + x[2], x[0] ** 3 - x[1]]).T
x = np.array([3, 5, 1])
f(x)

array([10, 22])

In [103]:
DF_forward_diff(f, x, 1e-6)

array([[ 6.      ,  0.      ,  1.      ],
       [27.000001, -1.      ,  0.      ]])

## Problem 9.8

In [113]:
def secent_minimizer(x_0, x_1, phi, eps, maxiter):
    x = np.array([x_0])
    fprime= np.array([DF_forward_diff(phi, x[0], eps)[0]])
    x = np.append(x, x_1)
    fprime = np.append(fprime, DF_forward_diff(phi, x[1], eps)[0])
    k = 2
    dist = 1000
    while dist > eps and k < maxiter:
            x_next = x[k - 1] - fprime[k-1]*((x[k-1] - x[k-2]) / (fprime[k-1] - fprime[k-2]))
            fprime_next = DF_forward_diff(phi, x_next, eps)[0]
            dist = np.abs((x_next - x[k-1]) / x[k-1])
            x = np.append(x, x_next)
            fprime = np.append(fprime, fprime_next)
            k += 1
    return x[k - 1]


def steepest_descent(f, x_0, eps, maxiter):
    dist = 1000
    i = 0
    x_k = x_0
    while dist > eps and i < maxiter:
        df = DF_forward_diff(f, x_k, 1e-6)[0]
        phi = lambda alpha: f(x_k - alpha*df.T)
        alpha_k = secent_minimizer(0.1, 0.8, phi, eps, maxiter)
        x_kp1 = x_k - alpha_k * df.T
        dist = la.norm(x_kp1 - x_k)
        x_k = x_kp1
        i += 1
    if i < maxiter:
        print("Converges in " + str(i) + " iterations")
        minvalue = f(x_k)
    else:
        print("Didn't converge")
        minvalue= None
    return x_k, minvalue


## Problem 9.9

In [120]:
f = lambda x: 100 * (x[1] - x[0] ** 2) ** 2 + (1 - x[0]) ** 2
x_0 = np.array([-2, 2])

In [126]:
(x, y), fxy = steepest_descent(f, x_0, 1e-8, 10000)
print('Minimizer: (', x,',', y, ')')
print('Minimum: ', fxy)

Converges in 1095 iterations
Minimizer: ( 0.9999949331364352 , 0.9999898410954257 )
Minimum:  2.5736626099348774e-11
