In [3]:
import numpy as np
import math


In [11]:
def function(x, y):
    a = 6 * y
    b = 6 * x + 8 * y + 1
    c = b
    d = 8 * x
    mat = np.matrix([[a, b],[c, d]])
    return mat

np.linalg.eigvals(function(-1/3, 0))

array([ 0.33333333, -3.        ])

In [7]:
np.linalg.eigvals(function(0, 0))

array([ 1., -1.])

In [8]:
np.linalg.eigvals(function(0, -1/4))

array([-2. ,  0.5])

In [10]:
np.linalg.eigvals(function(-1/9, -1/(12)))

array([-0.30854322, -1.08034567])